[package]
name = "parallel-tar"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.5"
rayon = "1.11.0"
tar = "0.4.40"
walkdir = "2.4.0"

[[bin]]
name = "parallel-tar"
path = "src/main.rs"

[[bin]]
name = "parallel-idx"
path = "src/indexer.rs"
